In [1]:
import pandas as pd
import numpy as np



In [2]:
# 讀取訓練和測試資料gene expression cancer RNA-Seq Data Set-20230503T055527Z-001\gene expression cancer RNA-Seq Data Set
train_label_csv = pd.read_csv("gene expression cancer RNA-Seq Data Set/train_label.csv")
train_data_csv = pd.read_csv("gene expression cancer RNA-Seq Data Set/train_data.csv")
test_label_csv = pd.read_csv("gene expression cancer RNA-Seq Data Set/test_label.csv")
test_data_csv = pd.read_csv("gene expression cancer RNA-Seq Data Set/test_data.csv")

In [3]:
print(train_label_csv.shape)
print(train_data_csv.shape)

(469, 2)
(469, 20532)


In [4]:
train_label_csv = train_label_csv.drop(columns=['id'])
data = train_data_csv.drop(columns=['id'])
test_label_csv = test_label_csv.drop(columns=['id'])
test_data_csv = test_data_csv.drop(columns=['id'])
train_data_csv=data


In [5]:
print(train_label_csv.shape)
print(train_data_csv.shape)

(469, 1)
(469, 20531)


In [6]:
from sklearn.preprocessing import OneHotEncoder

# 創建OneHotEncoder對象
enc = OneHotEncoder()

# 將訓練集和測試集的標籤都用於擬合Encoder
enc.fit(train_label_csv)

# 將訓練集和測試集的標籤都轉換成One-Hot編碼
label_encoder = enc.transform(train_label_csv).toarray()
print(label_encoder) #有3類
# 新增一個column並填入0
unknown_col = np.zeros((label_encoder.shape[0], 1))

# 將unknown column插入到最後一欄
label_encoder = np.hstack((label_encoder, unknown_col))

print(label_encoder.shape)

[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 ...
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]]
(469, 4)


In [7]:
pd.DataFrame(label_encoder)

0    1    2    3
0    0.0  1.0  0.0  0.0
1    1.0  0.0  0.0  0.0
2    0.0  0.0  1.0  0.0
3    1.0  0.0  0.0  0.0
4    1.0  0.0  0.0  0.0
..   ...  ...  ...  ...
464  0.0  1.0  0.0  0.0
465  0.0  0.0  1.0  0.0
466  1.0  0.0  0.0  0.0
467  0.0  1.0  0.0  0.0
468  1.0  0.0  0.0  0.0

[469 rows x 4 columns]

In [8]:
# 填補缺失值
data_no_na = np.array(pd.DataFrame(train_data_csv).fillna(pd.DataFrame(train_data_csv).mean()))
data_no_na

array([[ 0.        ,  3.0572423 ,  2.89582609, ...,  9.76386301,
         5.31547928,  1.40708078],
       [ 0.        ,  1.25628607,  2.15568448, ...,  9.41376754,
         8.07614218,  0.        ],
       [ 0.        ,  2.48098887,  2.56044595, ...,  8.84422557,
         4.17528506,  0.        ],
       ...,
       [ 0.        ,  2.14580786,  1.62246187, ..., 10.35090604,
         6.02093995,  0.        ],
       [ 0.        ,  3.02830393,  2.1561377 , ...,  9.22815971,
         4.40394255,  0.        ],
       [ 0.        ,  3.30891417,  3.99043758, ..., 10.21244775,
         5.64598692,  0.        ]])

In [9]:
from sklearn.model_selection import train_test_split

# 分割數據集和標籤為訓練集和測試集
train_data, test_data, train_label, test_label = train_test_split(data_no_na, label_encoder, test_size=0.2, random_state=42)


In [10]:
train_data

array([[ 0.        ,  2.65574107,  2.82154696, ...,  9.46119088,
         5.1103716 ,  0.        ],
       [ 0.        ,  1.09808263,  0.90249812, ...,  9.38984426,
         3.46601363,  0.58736499],
       [ 0.        ,  3.09205518,  2.21032652, ...,  9.92115066,
         4.96865297,  0.        ],
       ...,
       [ 0.        ,  4.53853816,  4.5243082 , ...,  9.40903446,
         2.97142399,  0.        ],
       [ 0.        ,  2.14977963,  2.82653832, ..., 10.25048792,
         6.38552077,  0.        ],
       [ 0.        ,  2.46472054,  3.25408   , ...,  9.21532186,
         4.56769146,  0.64883355]])

In [11]:
#標準化
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
train_data_scaled = scaler.fit_transform(train_data)
test_data_scaled = scaler.transform(test_data)

In [12]:
pd.DataFrame(train_data_scaled)

0         1         2         3         4      5         6      \
0   -0.181106 -0.158621 -0.050081 -0.101708 -0.156803    0.0 -0.667952   
1   -0.181106 -1.406812 -1.929637 -0.251160  2.371868    0.0 -1.944440   
2   -0.181106  0.191009 -0.648722 -1.351261  0.624215    0.0 -0.746667   
3   -0.181106  0.430724  0.431969  0.904104 -0.967281    0.0  0.876988   
4   -0.181106 -1.132700 -2.049721  0.249854  0.389845    0.0  0.282569   
..        ...       ...       ...       ...       ...    ...       ...   
370 -0.181106  0.067518 -0.973423  0.288435  0.631651    0.0  0.020956   
371 -0.181106 -0.938661 -0.664288 -0.468097 -1.213526    0.0 -1.332993   
372 -0.181106  1.350112  1.617639  0.650523 -0.602610    0.0  1.062666   
373 -0.181106 -0.564060 -0.045192  1.482243 -0.688004    0.0 -0.167784   
374 -0.181106 -0.311690  0.373551 -0.507742  0.676777    0.0 -1.104557   

        7         8         9      ...     20521     20522     20523  \
0   -0.314544 -0.142041 -0.051709  ...  0.082219  0.185712  0.802543   
1   -1.029926 -0.142041 -0.051709  ... -0.947269 -2.199373 -2.634465   
2    0.100597 -0.142041 -0.051709  ...  0.089101 -0.363457  0.431617   
3    0.031616 -0.142041 -0.051709  ...  0.602181  0.460031  0.333982   
4   -0.271460 -0.142041 -0.051709  ...  0.102717  1.403652  0.704306   
..        ...       ...       ...  ...       ...       ...       ...   
370  1.005511 -0.142041 -0.051709  ... -1.718737 -1.659511 -1.864595   
371 -1.029926 -0.142041 -0.051709  ... -0.111076 -0.785281 -1.023608   
372  0.823785 -0.142041 -0.051709  ... -0.589677 -0.616445  0.806009   
373 -0.241140 -0.142041 -0.051709  ...  0.431000  0.856828  0.069436   
374 -1.029926 -0.142041 -0.051709  ... -0.092858  0.449713  0.659872   

        20524     20525     20526     20527     20528     20529     20530  
0    0.965449  0.158116  0.231966 -1.567648 -0.198413 -0.279412 -0.265657  
1    0.227283 -0.900303  1.149547 -4.327214 -0.327460 -1.085753  1.141967  
2    0.310733  0.999599 -0.563499  0.010807  0.633532 -0.348907 -0.265657  
3    0.196405  0.211133  0.872822  0.372214  0.384823  1.383676 -0.265657  
4    0.527176  0.505493 -0.802277 -0.262949 -0.279212  0.542382  2.484339  
..        ...       ...       ...       ...       ...       ...       ...  
370  0.424935 -0.290611 -0.408150 -3.085714 -0.347307 -1.291200 -0.265657  
371  0.256747  1.230272  1.886341  0.425832 -0.713523 -0.158565 -0.265657  
372 -0.728740  1.178067 -0.300029 -0.329791 -0.292750 -1.328284 -0.265657  
373  0.047783 -0.123706  0.644093  0.072847  1.229215  0.345880 -0.265657  
374  0.207922 -0.829854 -0.223154 -0.352668 -0.643124 -0.545525  1.289277  

[375 rows x 20531 columns]

In [13]:
train_data_scaled.shape

(375, 20531)

In [14]:
#第一個參數為 train_data_scaled 和 test_data_scaled，分別代表經過標準化處理後的訓練集和測試集資料。
# 第二個參數中 (train_data_scaled.shape[0], train_data_scaled.shape[1], 1) 的含義為將原本的二維資料轉換成三維資料，其中新的第三維的大小為1。
# 這個新的維度的大小是由 LSTM 模型需要的資料格式決定的，其中第一個維度表示樣本數，第二個維度表示時間步長，第三個維度表示每個時間步中的特徵數
#將原本的二維資料轉換成三維資料，可以讓 LSTM 模型正確地理解資料

train_data_3d = np.reshape(train_data_scaled, (train_data_scaled.shape[0], train_data_scaled.shape[1], 1))
test_data_3d = np.reshape(test_data_scaled, (test_data_scaled.shape[0], test_data_scaled.shape[1], 1))


In [15]:
train_data_3d.shape

(375, 20531, 1)

In [16]:
import tensorflow as tf
from tensorflow import keras

In [17]:
# 建立模型
from keras.layers import Dropout, BatchNormalization
from keras import regularizers

model = keras.models.Sequential([
    keras.layers.LSTM(48, activation='tanh', return_sequences=False, input_shape=(train_data_3d.shape[1], train_data_3d.shape[2]), kernel_regularizer=regularizers.l2(0.001)),
    Dropout(0.1), #丟棄率為 0.1
    BatchNormalization(), #對上一層輸出進行標準化
    keras.layers.Dense(36, activation='relu', kernel_regularizer=regularizers.l2(0.001)), #輸入維度為 48，輸出維度為 36，激活函數為 relu
    Dropout(0.1),
    BatchNormalization(),
    keras.layers.Dense(24, activation='relu', kernel_regularizer=regularizers.l2(0.001)),
    Dropout(0.1),
    BatchNormalization(),
    keras.layers.Dense(18, activation='relu', kernel_regularizer=regularizers.l2(0.001)),
    Dropout(0.1),
    BatchNormalization(),
    keras.layers.Dense(4, activation='softmax', kernel_regularizer=regularizers.l2(0.001)) #表示預測出的結果屬於 9 個類別中的哪一個
])
#型使用 Adam 優化器，並定義了一個網格搜索需要用到的 learning_rate 參數
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.summary() #顯示整個模型的結構和參數數量等信息

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, 48)                9600      
                                                                 
 dropout (Dropout)           (None, 48)                0         
                                                                 
 batch_normalization (BatchN  (None, 48)               192       
 ormalization)                                                   
                                                                 
 dense (Dense)               (None, 36)                1764      
                                                                 
 dropout_1 (Dropout)         (None, 36)                0         
                                                                 
 batch_normalization_1 (Batc  (None, 36)               144       
 hNormalization)                                        

In [18]:
from sklearn.model_selection import KFold

# 定義交叉驗證參數
n_splits = 5 # 設置5折交叉驗證
fold = KFold(n_splits=n_splits, shuffle=True, random_state=42)
#每次選擇其中的k-1個分片作為訓練集，剩下的一個分片作為驗證集。
# 在進行k次交叉驗證時，每個分片都會被當做驗證集一次，因此我們可以得到k個模型，最終結果為這k個模型的平均值。

In [19]:
# 增加 callbacks:用於防止過擬合
# 在訓練期間，它會監視指定的度量，例如驗證集的損失或準確度。如果在指定的 epoch 數內，這個度量沒有再改善，則訓練會被停止。
# 在這個例子中，start_from_epoch 參數設置為 150，表示在 150 個 epoch 之後開始監控度量的改善。patience 參數設置為 50，
# 表示如果在接下來的 50 個 epoch 中度量沒有再改善，訓練將被停止。最後，restore_best_weights 參數設置為 True，表示在訓練停止後，
# 模型將被還原為具有最好權重的那個 epoch 的狀態。這樣可以確保模型在最佳狀態下被保存。
early_stopping = keras.callbacks.EarlyStopping(start_from_epoch=150 ,patience=50, restore_best_weights=True)

# 進行交叉驗證
scores = []
for train_index, test_index in fold.split(data):
    # 將數據分為訓練集和測試集
    X_train, X_test = train_data_csv.iloc[train_index], train_data_csv.iloc[test_index]
    y_train, y_test = label_encoder[train_index], label_encoder[test_index]

    # 標準化
    train_data_scaled = scaler.fit_transform(X_train)
    test_data_scaled = scaler.transform(X_test)

    train_data_3d = np.reshape(train_data_scaled, (train_data_scaled.shape[0], train_data_scaled.shape[1], 1))
    test_data_3d = np.reshape(test_data_scaled, (test_data_scaled.shape[0], test_data_scaled.shape[1], 1))

     # 編譯模型
    model.compile(loss='categorical_crossentropy', optimizer=optimizer, metrics=['accuracy'])

    # 訓練模型
    model.fit(train_data_3d, y_train, epochs=500, batch_size=64, validation_data=(test_data_3d, y_test), callbacks=[early_stopping])

    # 評估模型
    score = model.evaluate(test_data_3d, y_test, verbose=0)
    scores.append(score[1])

# 輸出交叉驗證結果
print("Cross-validation accuracy: %.2f%% (+/- %.2f%%)" % (np.mean(scores) * 100, np.std(scores) * 100))

Epoch 1/500
6/6 [==============================] - 75s 13s/step - loss: 1.9581 - accuracy: 0.2720 - val_loss: 1.4782 - val_accuracy: 0.4255
Epoch 2/500
6/6 [==============================] - 154s 27s/step - loss: 1.7829 - accuracy: 0.2827 - val_loss: 1.4668 - val_accuracy: 0.4468
Epoch 3/500
6/6 [==============================] - 216s 37s/step - loss: 1.6697 - accuracy: 0.3227 - val_loss: 1.4576 - val_accuracy: 0.3723
Epoch 4/500
6/6 [==============================] - 285s 48s/step - loss: 1.5944 - accuracy: 0.3440 - val_loss: 1.4478 - val_accuracy: 0.3298
Epoch 5/500
6/6 [==============================] - 321s 53s/step - loss: 1.5103 - accuracy: 0.3947 - val_loss: 1.4381 - val_accuracy: 0.3191
Epoch 6/500
6/6 [==============================] - 332s 55s/step - loss: 1.4572 - accuracy: 0.4133 - val_loss: 1.4292 - val_accuracy: 0.2872
Epoch 7/500
6/6 [==============================] - 357s 59s/step - loss: 1.4447 - accuracy: 0.4320 - val_loss: 1.4203 - val_accuracy: 0.2766
Epoch 8/500
6/

KeyboardInterrupt: 